"""add remind_days_before to tasks

Revision ID: 4c68e39a12a3
Revises: 8f3a500e1e75
Create Date: 2026-07-07 14:32:15.127828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c68e39a12a3'
down_revision: Union[str, Sequence[str], None] = '8f3a500e1e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('remind_days_before', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'remind_days_before')
    # ### end Alembic commands ###
